config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'

  get '/closed', to: 'public_pages#closed'

  namespace :admin do
    root 'pages#dashboard'
    resources :host_provider_accounts
  end

  resources :videos, only: [:index, :show, :edit, :update] do
    get :download, on: :member
    get 'page/:page', action: :index, on: :collection
  end

  resources :invites, only: [:index, :new, :create, :destroy]

  resources :passwords, controller: 'passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: 'passwords',
      only: [:edit, :update]
  end

  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :sender, required: true, class_name: 'User'
  belongs_to :recipient, required: false, class_name: 'User'

  before_save :set_email_case, if: :email_changed?
  before_save :check_existing_user

  validates :email, presence: true

  def check_existing_user
    existing_user = User.find_by(email: email)
    self.recipient_id = existing_user.id if existing_user
  end

  private

  def set_email_case
    email.downcase!
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  responders :flash, :http_cache, :collection

  respond_to :html

  before_action :require_login
  before_action :set_invite, only: [:edit, :update, :destroy]

  def index
    authorize(Invite)
    @invites = InviteDecorator.decorate_collection(policy_scope(Invite))
    respond_with(@invites)
  end

  def new
    @invite = Invite.new
    authorize(@invite)
    respond_with(@invite)
  end

  def create
    authorize(Invite)

    attributes = permitted_attributes(Invite)
    attributes.merge!(sender_id: current_user.id) unless attributes[:sender_id]

    @invite = CreateInvite.new(attributes).perform
    respond_with(@invite)
  end

  def destroy
    authorize(@invite)
    @invite.destroy
    respond_with(@invite)
  end

  private

  def set_invite
    @invite = Invite.find(params[:id])
  end
end

app/views/invites/index.html.haml
%h1 Invites
%table.table
  %thead
    %tr
      %th Email
      %th Created By
      %th Redeemed By
      %th Redeemed At
      %th Invite Link
      %th
  %tbody
    - @invites.each do |invite|
      %tr
        %th= invite.email
        %th= invite.created_by_user
        %th= invite.redeemed_by_user
        %th= invite.redeemed_at
        %th= invite.invite_link
        %td= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Invite', new_invite_path

app/views/invites/new.html.haml
%h1 New Invite

= simple_form_with_policy_for(@invite, policy: policy(@invite)) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :email
    = f.association :sender, label_method: :email, selected: current_user.id
    = f.input :role, collection: Roles.all.keys, selected: User.column_defaults['role']
  .form-actions
    = f.button :submit, class: 'btn-primary'

= link_to 'Back', invites_path