config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'

  get '/closed', to: 'public_pages#closed'

  namespace :admin do
    root 'pages#dashboard'
    resources :host_provider_accounts
  end

  resources :videos, only: [:index, :show, :edit, :update] do
    get :download, on: :member
    get 'page/:page', action: :index, on: :collection
  end

  resources :invites, only: [:index, :new, :create, :destroy]

  resources :passwords, controller: 'passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: 'passwords',
      only: [:edit, :update]
  end

  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'
end

app/models/video.rb
require 'shellwords'
require 'digest/md5'
require 'find'
require 'pathname'

class Video < ApplicationRecord
  has_one :snapshot_index
  delegate :snapshots, to: :snapshot_index

  has_many :source_files
  belongs_to :primary_source_file, class_name: 'SourceFile'

  has_many :uploads

  before_create :set_name

  has_paper_trail ignore: [:file_metadata]

  # From the samples I used this value is 1.333.
  NON_SQUARE_PIXEL_ASPECT_RATIO = (1.1..)

  # This only covers 2000-2019 videos.
  # TODO: figure out a way to configure this
  ASSUMED_YEAR_CENTURY = '20'
  NUMERAL_DATE_REGEX = /
    (?<year>(20)?(01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19))
    (?<separator>\.|\-|\/)?
    (?<month>0[1-9]|1[012])
    (\k<separator>)?
    (?<day>0[1-9]|\.[1-9]|[12][0-9]|3[01])
  /x

  update_index('videos#video') { self }

  def self.scan(path, options = {})
    VideoScanner.new(path, options).perform
  end

  def self.formated_duration_from_seconds(duration)
    Time.at(duration).utc.strftime("%H:%M:%S")
  end

  def self.without_snapshot_index
    left_joins(:snapshot_index).where(snapshot_indices: { video_id: nil })
  end

  def self.without_uploads
    left_joins(:uploads).where(uploads: { video_id: nil })
  end

  def self.with_multiple_source_files
    # FIXME: This scope doesn't behave as expected when calling `count` on the results.
    left_joins(:source_files).having('count(source_files.id) > 0').group('videos.id')
  end

  def upload_to(provider_name, account:, remote_path: nil)
    UploadVideo.new(self,
      provider_name,
      account: account,
      remote_path: remote_path
    ).perform
  end

  def file_metadata
    super&.with_indifferent_access
  end

  def file_path
    SourceFile.find(primary_source_file_id).path
  end

  def default_name
    [
      formated_air_date,
      File.basename(file_path, file_ext)
    ].join(' ')
  end

  def file_ext
    File.extname(file_path)
  end

  def formated_duration
    self.class.formated_duration_from_seconds(duration.to_f) if duration
  end

  def formated_air_date
    "#{air_date.strftime('%Y.%m.%d')}" if air_date
  end

  def file_size
    if file_metadata.present?
      file_metadata[:general].first[:file_size].to_i
    end
  end

  def set_duration
    if file_metadata.present?
      self.duration = file_metadata[:general].first[:duration].to_f
    end
  end

  def non_square_pixel?
    NON_SQUARE_PIXEL_ASPECT_RATIO.cover?(pixel_aspect_ratio)
  end

  def calculated_width
    width * pixel_aspect_ratio
  end

  def height
    @height ||= file_metadata[:video].first[:height].gsub(/\D/, '').to_i
  end

  def width
    @width ||= file_metadata[:video].first[:width].gsub(/\D/, '').to_i
  end

  def pixel_aspect_ratio
    @pixel_aspect_ratio ||= file_metadata[:video].first[:pixel_aspect_ratio].to_f
  end

  def set_air_date
    match = NUMERAL_DATE_REGEX.match(name)
    if match
      # TODO: Should figure out a better way to do this
      year = match[:year]
      year.prepend(ASSUMED_YEAR_CENTURY) if year.length == 2

      self.air_date = DateTime.strptime(
        "#{year}-#{match[:month]}-#{match[:day]}",
        '%Y-%m-%d'
      )
    end
  end

  def set_name
    self.name = default_name
  end

  def set_metadata
    raw_response = %x[mediainfo #{file_path.shellescape} --output=XML]
    parsed_response = Nori.parse(raw_response)[:media_info][:media]

    self.file_metadata = parsed_response[:track].group_by do |track|
      track.delete(:type).downcase
    end
  end

  # Calculates a hash for the video using a portion of the file,
  def set_file_hash
    self.file_hash = if File.size(file_path) < 6.megabytes
      # File is too small to seek to 5MB, so hash the whole thing
      Digest::MD5.hexdigest(IO.binread(file_path))
    else
      Digest::MD5.hexdigest(File.open(file_path, 'rb') do |f|
        f.seek(5.megabytes) && f.read(1.megabyte)
      end)
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  respond_to :html, :json

  before_action :set_video, only: [:show, :edit, :update, :download]

  def index
    authorize(Video)
    if query.present?
      @videos = VideosIndex::Video.query(match: { name: query })
        .order(sort_column(search_sort_columns) => sort_direction)
        .page(page).per(per_page)
    else
      @videos = Video.order(sort_column => sort_direction)
        .page(page).per(per_page)
    end

    respond_with(@videos)
  end

  def show
    authorize(@video)
    @uploads = policy_scope(@video.uploads)
    @snapshots = @video.snapshots.processed.order(video_time: :asc)
    respond_with(@video)
  end

  def edit
    authorize(@video)
    respond_with(@video)
  end

  def update
    authorize(@video)
    @video.update(video_params)
    respond_with(@video)
  end

  def download
    authorize(@video)
    if download_url = video.download_url
      redirect_to(download_url)
    else
      send_file(video.file_path, filename: video.name)
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:name, :external_id, :air_date)
  end

  def query
    params.dig(:search, :value)
  end

  def sort_direction
    sort_options&.fetch(:dir) || :desc
  end

  # Elasticsearch columns that are indexed for advanced search can't be sorted.
  # To get around this you can create sortable duplicates of the columns
  # that have a keyword type which can be sorted.
  def search_sort_columns
    %w[name_sortable air_date file_hash external_id]
  end

  def index_sort_columns
    %w[name air_date file_hash external_id]
  end

  def sort_column(column_list = index_sort_columns)
    return column_list.first unless sort_options
    column_list[sort_options[:column].to_i]
  end

  def sort_options
    params.dig(:order, '0')
  end

  def page
    params[:page] || params[:start].to_i / per_page + 1
  end

  def per_page
    params[:length].to_i > 0 ? params[:length].to_i : 10
  end
end

app/helpers/video_helper.rb
module VideoHelper
  def table_view?
    params[:view_type] == 'table'
  end

  def thumbnail_view?
    !table_view?
  end

  def escape_snapshot_url(url)
    url_array = File.split(url)
    url_array << CGI.escape(url_array.pop)
    File.join(url_array)
  end

  def view_type
    params[:view_type] || 'thumbnails'
  end
end

app/views/videos/edit.html.haml
%section
  %h2 Editing Video
  = simple_form_for @video do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
    .form-inputs
      = f.input :name
      = f.input :air_date, as: :string, input_html: { value: localize(f.object.air_date, format: "%Y.%m.%d") }
      = f.input :external_id, label: 'External ID'
    .form-actions
      = f.button :submit, class: 'btn-primary'

app/views/videos/index.html.haml
.view-links
  = link_to('Thumbnail View', videos_path(view_type: 'thumbnails'), class: "btn btn-light #{'active' if thumbnail_view?}")
  = link_to('Table View', videos_path(view_type: 'table'), class: "btn btn-light #{'active' if table_view?}")

%section
  = render "videos/index/#{view_type}"

app/views/videos/show.html.haml
.page-header.pb-2.mt-4.mb-2.border-bottom
  %h1= @video.name
  - if policy(@video).download?
    %a.btn.btn-primary{href: download_video_path(@video)}
      %i.icon-download-alt.icon-white
      Download
  - if policy(@video).edit?
    %a.btn.btn-primary{href: edit_video_path(@video)}
      %i.icon-edit.icon-white
      Edit

.slider-container.col-10
  %ul.snapshots.row
    - @snapshots.each do |snapshot|
      %li.col-12
        = image_tag(escape_snapshot_url(url_for(snapshot.image.variant(resize_to_limit: [775, 775]))))
        %p.timestamp=snapshot.formated_video_time

  %ul.rslides_tabs.rslides1_tabs.row
    - @snapshots.each_with_index do |snapshot, i|
      %li
        = link_to '#', class: "rslides1_s#{i + 1}" do
          = image_tag(escape_snapshot_url(url_for(snapshot.image.variant(resize_to_fill: [75, 75]))))

%section.extra-info.col-10
  %h3 Extra Info
  .accordion
    .card.bg-light
      .card-body
        %ul.accordion-inner.unstyled.well
          %li
            %strong File Hash:
            = @video.file_hash
          %li
            %strong Air Date:
            = @video.formated_air_date
          %li
            %strong External ID:
            = @video.external_id
          %li
            %strong Index Image:
            = link_to 'View', @video.snapshot_index.image

- if policy(Upload).index?
  %section.uploads.col-10
    %h3 External Uploads
    .card.bg-light
      .card-body
        - if @uploads.empty?
          No External Uploads
        - @uploads.each do |upload|
          = link_to upload.host_provider.name, upload.url, class: 'btn btn-primary'

%section.metadata.col-10#metadata
  %h3 Metadata
  .accordion
    - @video.file_metadata&.each do |section_name, section_content|
      .card.bg-light
        .card-header
          %h4
            %button.btn.btn-link.collapsed{ type: 'button', data: { toggle: 'collapse', target: "##{section_name}-metadata" }, aria: { expanded: false, controls: "#{section_name}-metadata" }}
              = section_name.titleize
        .collapse{ id: "#{section_name}-metadata", data: { parent: '#metadata' }}
          .card-body
            %ul.accordion-inner.unstyled.well
              - section_content.first.each do |name, value|
                %li
                  %strong #{name.titleize}:
                  = value