config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'

  get '/closed', to: 'public_pages#closed'

  namespace :admin do
    root 'pages#dashboard'
    resources :host_provider_accounts
  end

  resources :videos, only: [:index, :show, :edit, :update] do
    get :download, on: :member
    get 'page/:page', action: :index, on: :collection
  end

  resources :invites, only: [:index, :new, :create, :destroy]

  resources :passwords, controller: 'passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: 'passwords',
      only: [:edit, :update]
  end

  get '/sign_in' => 'sessions#new', as: 'sign_in'
  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'
end

app/models/host_provider_account.rb
class HostProviderAccount < ApplicationRecord
  belongs_to :host_provider
  has_many :uploads

  validates :username, presence: true
  validates :password, presence: true

  validates :host_provider, presence: true
  validates :name, presence: true, if: -> { host_provider.name == 'mega' }

  def self.online
    where(online: true)
  end

  def self.for_provider(provider)
    joins(:host_provider).where(host_providers: { name: provider })
  end

  def client
    @client ||= HostProviders[host_provider.name].new(
      username: username,
      password: password
    )
  end

  def free_storage
    total_storage - used_storage
  end

  def check_and_update_free_space
    if client.check_usage?
      update(used_storage: client.status[:used_storage])
    end
  end
end

app/controllers/admin/host_provider_accounts_controller.rb
module Admin
  class HostProviderAccountsController < ApplicationController
    respond_to :html

    before_action :require_login
    before_action :set_host_provider_account, only: [:show, :edit, :update, :destroy]

    def index
      authorize(HostProviderAccount)
      @host_provider_accounts = policy_scope(HostProviderAccount)
      respond_with(@host_provider_accounts)
    end

    def show
      authorize(@host_provider_account)
      respond_with(@host_provider_account)
    end

    def new
      @host_provider_account = HostProviderAccount.new
      authorize(@host_provider_account)
      respond_with(@host_provider_account)
    end

    def edit
      authorize(@host_provider_account)
      respond_with(@host_provider_account)
    end

    def create
      authorize(HostProviderAccount)
      @host_provider_account = HostProviderAccount.create(host_provider_account_params)
      respond_with(@host_provider_account)
    end

    def update
      authorize(@host_provider_account)
      @host_provider_account.update(host_provider_account_params)
      respond_with(@host_provider_account)
    end

    def destroy
      authorize(@host_provider_account)
      @host_provider_account.destroy
      respond_with(@host_provider_account)
    end

    private

    def set_host_provider_account
      @host_provider_account = HostProviderAccount.find(params[:id])
    end

    def host_provider_account_params
      params.require(:host_provider_account).permit(
        :host_provider_id, :name, :username, :password, :online, :total_storage
      )
    end
  end
end

app/helpers/host_provider_accounts_helper.rb
module HostProviderAccountsHelper
end

app/views/host_provider_accounts/_form.html.haml
= simple_form_for(@host_provider_account) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.association :host_provider, label_method: :name, value_method: :id, include_blank: false
    = f.input :name
    = f.input :username
    = f.input :password
    = f.input :online
    = f.input :total_storage
    = f.input :used_storage, disabled: true
  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/host_provider_accounts/edit.html.haml
%section
  %h2 Editing Host Provider Account
  = render 'form', host_provider_account: @host_provider_account

= link_to 'Show', @host_provider_account
= link_to 'Back', host_provider_accounts_path

app/views/host_provider_accounts/index.html.haml
%h1 Host Provider Accounts
%table.table
  %thead
    %tr
      %th Provider
      %th Username
      %th Online
      %th Used Storage
      %th Total Storage
      %th{colspan: '3'}
  %tbody
    - @host_provider_accounts.each do |host_provider_account|
      %tr
        %th= host_provider_account.host_provider.name
        %th= host_provider_account.username
        %th= host_provider_account.online
        %th= host_provider_account.used_storage
        %th= host_provider_account.total_storage
        %td= link_to 'Show', host_provider_account
        %td= link_to 'Edit', edit_host_provider_account_path(host_provider_account)
        %td= link_to 'Destroy', host_provider_account, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Host Provider Account', new_host_provider_account_path

app/views/host_provider_accounts/new.html.haml
%h1 New Host Provider Account
= render 'form', host_provider_account: @host_provider_account
= link_to 'Back', host_provider_accounts_path

app/views/host_provider_accounts/show.html.haml
%section
  %h2 Host Provider Account: #{@host_provider_account.username}
  %dl.dl-horizontal
    %dt
      %strong Host Provider:
    %dd= @host_provider_account.host_provider.name

    %dt
      %strong Name:
    %dd= @host_provider_account.name

    %dt
      %strong Username:
    %dd= @host_provider_account.username

    %dt
      %strong Online:
    %dd= @host_provider_account.online

    %dt
      %strong Total Storage:
    %dd= @host_provider_account.total_storage

    %dt
      %strong Used Storage:
    %dd= @host_provider_account.used_storage

    %dt
      %strong Upload Count:
    %dd= @host_provider_account.uploads.count

  = link_to 'Edit', edit_host_provider_account_path(@host_provider_account)
  = link_to 'Back', host_provider_accounts_path